### ISSUE TITLE
query Builder Tests failing

### ISSUE THREAD

**Issue by STiAT** [FredrikLandstrom/node-omnibus#1]
The Connection.js actually returns the promise object, not the resolved object. I'm guessing this happens on other functions as well, but the queryBuilder test fails..

```
{ _bitField: 268435456,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _progressHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: 
   { payload: { rowset: [Object] },
     method: 'GET',
     collist: '',
     path: 'alerts/status',
     orderBy: 'Serial',
     filter: 'Serial%20%3E%201%20and%20Serial%20%3C%2010' } }
```

I've been looking into this, but since I'm new to node.js and generally javascript, I couldn't find the mistake. Though, it seems that the implementation compared to all the "how to use promises" is .. pretty strange.

**Comment by FredrikLandstrom** [comment]
Hi! Thank you for the issue report, I´ll look into it. Can you look in your /package.json file and give me the version?

```
{
  "name": "node-omnibus",
  "version": "0.2.3",
```

**Comment by FredrikLandstrom** [comment]
Also, it would be a great help for me if you have a small example code to demonstrate the problem. The tests (npm test) are not complete and need more work to make good tests.

**Comment by FredrikLandstrom** [comment]
Error could not be replicated. Please reopen if error still exists.
